=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/DTD10-10-2014.dtd
<!ELEMENT transcription (page, annotation)>
<!ELEMENT page EMPTY>
	<!ATTLIST page filename CDATA #REQUIRED>
	<!ATTLIST page pagination CDATA #IMPLIED>
	<!ATTLIST page signature CDATA #IMPLIED>
	<!ATTLIST page reader CDATA #REQUIRED>

<!ELEMENT annotation (marginalia*, underline*, symbol*, mark*)>	
	<!ELEMENT marginalia (language*, translation?)>
	<!ATTLIST marginalia hand (English_secretary|Italian) #REQUIRED>
	<!ATTLIST marginalia date CDATA #IMPLIED>
	<!ATTLIST marginalia other_reader CDATA #IMPLIED>
	<!ATTLIST marginalia topic (Law|Astronomy|Warfare|Rhetoric) #IMPLIED> 
	<!ATTLIST marginalia anchor_text CDATA #IMPLIED>
	 	<!ELEMENT language (position*)>
			<!ATTLIST language ident (EN|EL|FR|IT|LA|ES) #REQUIRED> 
				<!ELEMENT position (marginalia_text*, person*, book*, location*, X-ref*, emphasis*)>
					<!ATTLIST position place (head|tail|left_margin|right_margin|intext|full_page) #REQUIRED>
					<!ATTLIST position book_orientation	(0|90|180|270) #REQUIRED>
						<!ELEMENT marginalia_text (#PCDATA)>
						<!ELEMENT person EMPTY>
							<!ATTLIST person name CDATA #REQUIRED>
						<!ELEMENT book EMPTY>
							<!ATTLIST book title CDATA #REQUIRED>
						<!ELEMENT location EMPTY>
							<!ATTLIST location name CDATA #REQUIRED>
						<!ELEMENT X-ref EMPTY>
							<!ATTLIST X-ref person CDATA #REQUIRED>
							<!ATTLIST X-ref book_title CDATA #REQUIRED>
						<!ELEMENT emphasis EMPTY> 
							<!ATTLIST emphasis method (chalk|pen) #REQUIRED>
							<!ATTLIST emphasis text CDATA #IMPLIED>
		<!ELEMENT translation (#PCDATA)>
	<!ELEMENT underline EMPTY>
		<!ATTLIST underline method (chalk|pen) #REQUIRED>
		<!ATTLIST underline type (straight|curved) #REQUIRED>
		<!ATTLIST underline language (EN|EL|FR|IT|LA|ES) #REQUIRED>
		<!ATTLIST underline text CDATA #IMPLIED> 
	<!ELEMENT symbol EMPTY>
		<!ATTLIST symbol name (Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun) #REQUIRED>
		<!ATTLIST symbol place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST symbol language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST symbol text CDATA #IMPLIED>
	<!ELEMENT mark EMPTY>
		<!ATTLIST mark name	(apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign) #REQUIRED>
		<!ATTLIST mark method (chalk|pen) #REQUIRED>
		<!ATTLIST mark place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST mark language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST mark text CDATA #IMPLIED>
			
<!ENTITY agrave "à">
<!ENTITY aacute "á">
<!ENTITY atiled "ã">
<!ENTITY egrave "è">
<!ENTITY eacute "é">
<!ENTITY ecirc "ê">
<!ENTITY igrave "ì">
<!ENTITY ograve "ò">
<!ENTITY oacute "ó">
<!ENTITY Ocirc "Ô">
<!ENTITY euml "ë">
<!ENTITY ugrave "ù">

=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/Domenichi/Ha2.009r.xml
<?xml version="1.0" standalone="no" ?>

<!DOCTYPE transcription SYSTEM "DTD10-10-2014.dtd">

<transcription>
    <page filename="Ha2.009r.tif" pagination="337" reader="Harvey"/>	<!-- ABO 13right -->
    <annotation>
        
        <!-- Marginalia -->
        <marginalia hand="Italian">
            <language ident="IT">
                <position place="head" book_orientation="0">
                    <marginalia_text>
                      Pontano, mirabilmente piaceuole.
                    </marginalia_text>
                	<person name="Giovanni Pontano"/>
                </position>
            </language>
        </marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="head" book_orientation="0">
    				<marginalia_text>
    					) Vita Eutuchi.
    				</marginalia_text>
    				<person name="Eutuchus"/> <!-- Another creation of Harvey's  --> 
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="right_margin" book_orientation="0">
    				<marginalia_text>
    					Amore, non Inuidia.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					Barlandus varia ex Pontano. 
    				</marginalia_text>
    				<person name="Adrianus Barlandus"/>
    				<person name="Giovanni Pontano"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					Continual | emproouement of eueri part. 
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					vno, come superiore &agrave; tutti.
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					) { Giulio [secon]do
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="left_margin" book_orientation="90">
    				<marginalia_text>
    					Not the talnes, or lownes; but the worthines, or vnworthines ma[ke]s, or marres.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="right_margin" book_orientation="90">
    				<marginalia_text>
    					Solo mihi vita est, in dictis emphasis; actis
    					Dexteritas; rerum copia; laetus agon. }
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="right_margin" book_orientation="270">
    				<marginalia_text>
    					Aurei saeculi, heroiciq[ue] mundi instaurator;
    					Eutuchus dica[m], an Chrysotechnus?
    				</marginalia_text>
    				<person name="Eutuchus"/>
    				<person name="Chrysotechnus"/>
    			</position>
    		</language>
    	</marginalia>
        
        
        <!-- Underlines -->
        
    	<underline method="pen" type="straight" language="IT" text="daua la pappa a un"/>
    	<underline method="pen" type="straight" language="IT" text="si raffreddasse all'aria"/>
    	<underline method="pen" type="straight" language="IT" text="con gli scherzi tentare"/>
    	<underline method="pen" type="straight" language="IT" text="l'animo del bambino"/>
    	<underline method="pen" type="straight" language="IT" text="la scodella fuor"/>
    	<underline method="pen" type="straight" language="IT" text="tosto, huomo"/>
    	<underline method="pen" type="straight" language="IT" text="mangia questa pappa"/>
    	<underline method="pen" type="straight" language="IT" text="questo bambino non la uuol"/>
    	<underline method="pen" type="straight" language="IT" text="la scodella di"/>
    	<underline method="pen" type="straight" language="IT" text="con terribil grido"/>
    	<underline method="pen" type="straight" language="IT" text="sua scudella"/>
    	<underline method="pen" type="straight" language="IT" text="uillania"/>
    	<underline method="pen" type="straight" language="IT" text="ladro"/>
    	<underline method="pen" type="straight" language="IT" text="assassino, ghiotto"/>
    	<underline method="pen" type="straight" language="IT" text="impiccato"/>
    	<underline method="pen" type="straight" language="IT" text="&amp; moltre altre"/>
    	<underline method="pen" type="straight" language="IT" text="egli si rideua"/>
    	<underline method="pen" type="straight" language="IT" text="rendere la scodella"/>
    	<underline method="pen" type="straight" language="IT" text="finche non hebbe mangiato la pappa"/>
    	<underline method="pen" type="straight" language="IT" text="non hauere mangiato mai co[n]"/>
    	<underline method="pen" type="straight" language="IT" text="allhora, alle uillanie di"/>
    	<underline method="pen" type="straight" language="IT" text="quella donna"/>
    	<underline method="pen" type="straight" language="IT" text="Parasitico"/>
    	<underline method="pen" type="straight" language="IT" text="dalla Rouere"/>
    	<underline method="pen" type="straight" language="IT" text="nipote di Papa Giulio secondo"/>
    	<underline method="pen" type="straight" language="IT" text="speranza, &amp; pieno di tanta cortesia, &amp; magnanimit&agrave;"/>
    	<underline method="pen" type="straight" language="IT" text="quanto alcuno altro mai del Collegio de'"/>
    	<underline method="pen" type="straight" language="IT" text="di ridergli in uiso"/>
    	<underline method="pen" type="straight" language="IT" text="spalle"/>
    	<underline method="pen" type="straight" language="IT" text="sedere nel luogo suo"/>
    	<underline method="pen" type="straight" language="IT" text="che more[n]do"/>
    	<underline method="pen" type="straight" language="IT" text="egli nel"/>
    	<underline method="pen" type="straight" language="IT" text="la morte"/>
    	<underline method="pen" type="straight" language="IT" text="la uita di Sisto"/>
    	<underline method="pen" type="straight" language="IT" text="nipote"/>
    	<underline method="pen" type="straight" language="IT" text="lui del Papa"/>
    	<underline method="pen" type="straight" language="IT" text="herede"/>
    	<underline method="pen" type="straight" language="IT" text="ma no[n]"/>
    	<underline method="pen" type="straight" language="IT" text="della virt&ugrave; dell'animo, ne dell'altre ottime sue parti."/>
    
        
        <!-- Symbols: Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun -->
        
        <symbol name="Sun" place="right_margin"/>
    	<symbol name="SS" place="right_margin"/>
    	<symbol name="SS" place="tail"/>
    	<symbol name="JC" place="tail"/>
        
        <!-- Marks: apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|tilde|triple_dash|vertical_bar|X_sign -->
    	
    	<!-- Right margin -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- pappa a un -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- per es-->
    	<mark name="horizontal_bar" method="pen" place="right_margin"/> <!-- questa pappa: -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- Vdendo -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- ella la -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- do -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- uilla- -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- pero le -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- maggior -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- quel -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- magna -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- Cardi -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- fio -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- Sisto -->
    	
    	
    	<!-- Left margin -->
    	<mark name="straight_quotation_mark" method="pen" place="left_margin"/> <!-- re della sua -->
    
    	<!-- Intext -->
    	<mark name="quotation_mark" method="pen" place="intext"/> <!-- sfacciato.] -->
    	<mark name="plus_sign" method="pen" place="intext" language="IT" text="magnanimit&agrave;" />
    	<mark name="quotation_mark" method="pen" place="intext" language="IT" text="diridergli"/>
    	<mark name="straight_quotation_mark" method="pen" place="intext" language="IT" text="spalle"/>
    	<mark name="dot" method="pen" place="intext"/> <!-- grandezza, fu -->
    	<mark name="plus_sign" method="pen" place="intext" language="IT" text="morte"/>
    	<mark name="dot" method="pen" place="intext"/> <!-- Papa, dal -->
    	<mark name="dot" method="pen" place="intext"/> <!-- Galeotto, ma -->
    	
    	<mark name="vertical_bar" method="chalk" place="intext"/> <!-- Middle of page to the left -->
    	

    </annotation>
</transcription>

=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/Livy/00000014.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE transcription SYSTEM "DTD10-10-2014.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/User1/Documents/GitHub/AORCLONEJG/XMLschema/Harveyschema17102014.xsd">
    
    <page filename="00000014.tif" signature="[a4v]" reader="Harvey" />
    <annotation>
        <underline method="pen" type="straight" language="LA" text="PONDERVM VARIETAS"/>
        <underline method="pen" type="straight" language="LA" text="nona parte grauius"/>
        <underline method="pen" type="straight" language="LA" text="mel uino tertia fer&egrave;"/>
        <underline method="pen" type="straight" language="LA" text="Aqua proxim&egrave; ad uinum pondere"/>
        <underline method="pen" type="straight" language="LA" text="auena, far hordeo, triticum farre"/>
        <underline method="pen" type="straight" language="LA" text="triticum tritico grauius"/>
        
        <mark name="equal_sign" method="pen" place="right_margin"/>
        <mark name="dot" method="pen" place="intext"/> <!-- reperitur, at- -->
    </annotation>
</transcription>

=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/Livy/00000011.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE transcription SYSTEM "DTD10-10-2014.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/User1/Documents/GitHub/AORCLONEJG/XMLschema/Harveyschema17102014.xsd">
    
    <page filename="00000011.tif" signature="[a3r]" reader="Harvey" />
    <annotation>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>Nota[e] solae notabiles, relicta[e]: reliqua[e], resecta[e].</marginalia_text>
                </position>
            </language>
            <translation> Only the noteworthy notes are left, the others have been cut.</translation>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="tail" book_orientation="0">
                    <marginalia_text>Liuius, Romana[e] historia[e] facil&egrave; princeps. Singuli
                    libri, in suo genere pra[e]stantissimi. Pulcherrimorum mnemosynoru[m] mira
                    varietas. Nemo historicorum aut magis serio obseruat, aut tam graphi&egrave; pingit. 
                    Hunc nesciunt, qui vel Gra[e]cos historicos nimium admirantur, vel alios Romanos immoderat&egrave;
                    efferunt. Mihi cordi est, omne elocutionis, prudentia[e]q[ue] punctum in Liuio peruestigare.
                    De stylo Liuiano, pra[e]sertim in concionibus, meam inf&agrave; sententiam attexui.</marginalia_text>
                    <person name="Livy"/>
                </position>
            </language>
            <translation>Livy is easily the master of Roman history. Every single book is the most outstanding in its sort. 
                There is a wonderful diversity of the most beautiful memorials. None of the historians observes more earnestly, 
                or depicts so vividly. Those who marvel excessively at the Greek historians, 
                or immoderately exalt other Roman historians do not know him. 
                It is a delight for me to analyze every point of eloquence and sagacity in Livy in detail. 
                As for Livyâ€™s style, especially in the speeches, I have attached my assessment below.</translation>
        </marginalia>
        
        <underline method="pen" type="straight" language="LA" text="sol&ugrave;m Liuium emandauimus"/>
        <underline method="pen" type="straight" language="LA" text="quodammodo illustrauimus"/>
        <underline method="pen" type="straight" language="LA" text="sed mensuraru[m]"/>
        <underline method="pen" type="straight" language="LA" text="req[ue]; numaria"/>
        <underline method="pen" type="straight" language="LA" text="ad uyeterm historia[m] intelligendam"/>
        <underline method="pen" type="straight" language="LA" text="vitamq[ue]; co[m]munem gubernandam"/>
        <underline method="pen" type="straight" language="LA" text="uectigaliu[m]"/>
        <underline method="pen" type="straight" language="LA" text="pensionum"/>
        <underline method="pen" type="straight" language="LA" text="fructuum summas intelligent"/>
        <underline method="pen" type="straight" language="LA" text="precia estimabunt"/>
        <underline method="pen" type="straight" language="LA" text="ad nostri temporis"/>
        <underline method="pen" type="straight" language="LA" text="ponderu[m] mensurarumq[ue]; ratione instructi"/>
        <underline method="pen" type="straight" language="LA" text="mensuris"/>
        <underline method="pen" type="straight" language="LA" text="ponderibus"/>
        <underline method="pen" type="straight" language="LA" text="pecuniaru[m]q[ue]"/>
        <underline method="pen" type="straight" language="LA" text="Duo"/>
        <underline method="pen" type="straight" language="LA" text="ea ipsa"/>
        <underline method="pen" type="straight" language="LA" text="locorum"/>
        <underline method="pen" type="straight" language="LA" text="locorum"/>
        <underline method="pen" type="straight" language="LA" text="h[a]ec quoq[ue] pars" />
        <underline method="pen" type="straight" language="LA" text="Leonardo Poritio Vicentino"/>
        <underline method="pen" type="straight" language="LA" text="Gul. Budaeo"/>
        <underline method="pen" type="straight" language="LA" text="Andrea Alciato"/>
        <underline method="pen" type="straight" language="LA" text="Georgio Agricola"/>
        <underline method="pen" type="straight" language="LA" text="ex illorum uarijs copiosisq[ue]"/>
        <underline method="pen" type="straight" language="LA" text="saepe inter se dissidentibus sententijs"/>
        <underline method="pen" type="straight" language="LA" text="certam aliquam"/>
        <underline method="pen" type="straight" language="LA" text="eamq[ue] ordine describere"/>
        <underline method="pen" type="straight" language="LA" text="Liuio, Romanae historiae facil&egrave; principe"/>
        <underline method="pen" type="straight" language="LA" text="longae inquisitionis"/>
        <underline method="pen" type="straight" language="LA" text="quae res"/>
        <underline method="pen" type="straight" language="LA" text="mod&ograve; historiae"/>
        <underline method="pen" type="straight" language="LA" text="etiam Iurisconsultis"/>
        <underline method="pen" type="straight" language="LA" text="medicinaeq[ue] studiosis, utilis erit"/>
        <underline method="pen" type="straight" language="LA" text="Latinis sol&ugrave;m ponderibus"/>
        <underline method="pen" type="straight" language="LA" text="Graecis intelligendis"/>
        <underline method="pen" type="straight" language="LA" text="Doctorum"/>
        <underline method="pen" type="straight" language="LA" text="annotationes &amp;"/>
        <underline method="pen" type="straight" language="LA" text="ut uno ordine, unaq[ue] serie, suis aptis &amp;"/>
        <underline method="pen" type="straight" language="LA" text="partim leues"/>
        <underline method="pen" type="straight" language="LA" text="falsae"/>
        <underline method="pen" type="straight" language="LA" text="non necessarie"/>
        <underline method="pen" type="straight" language="LA" text="ijs mod&ograve; relictis"/>
        <underline method="pen" type="straight" language="LA" text="insignem aliquam utilitatem continerent"/>
        <underline method="pen" type="straight" language="LA" text="de Liuio ipso"/>
        <underline method="pen" type="straight" language="LA" text="Liuius ipse dignus alioquisit, qui semper"/>
        <underline method="pen" type="straight" language="LA" text="laudetur, placeat, uigeat, relegatur, ametur"/>
        
        <symbol name="SS" place="right_margin" />
        <symbol name="JC" place="right_margin"/>
        <symbol name="SS" place="intext"/> <!-- sem- -->
        
        <mark name="equal_sign" method="pen" place="left_margin"/>
        <mark name="equal_sign" method="pen" place="left_margin"/>
        <mark name="X_sign" method="pen" place="right_margin"/> <!--numaria-->
        <mark name="X_sign" method="pen" place="right_margin"/> <!--numaria-->
        <mark name="quotation_mark" method="pen" place="right_margin"/> <!--intelligendam-->
        <mark name="straight_quotation_mark" method="pen" place="right_margin"/> 
        <mark name="straight_quotation_mark" method="pen" place="right_margin"/> 
        <mark name="straight_quotation_mark" method="pen" place="right_margin"/> 
        <mark name="straight_quotation_mark" method="pen" place="right_margin"/> 
        <mark name="straight_quotation_mark" method="pen" place="right_margin"/> 
        <mark name="X_sign" method="pen" place="right_margin"/> <!--medico-->
        <mark name="equal_sign" method="pen" place="right_margin"/> <!--aliquam-->
        <mark name="equal_sign" method="pen" place="right_margin"/> <!-- fri- -->
        <mark name="dash" method="pen" place="right_margin"/> <!--grafiti-->
        <mark name="dash" method="pen" place="right_margin"/> <!--scho-->
        <mark name="dash" method="pen" place="right_margin"/> <!--quaeren-->
        
        <mark name="dot" method="pen" place="intext"/> <!--co[n]suleremus, non-->
        <mark name="plus_sign" method="pen" place="intext" language="LA" text="mensuraru[m]"/> 
        <mark name="plus_sign" method="pen" place="intext" language="LA" text="po[n]derum"/> 
        <mark name="plus_sign" method="pen" place="intext" language="LA" text="po[n]derum"/>
        <mark name="plus_sign" method="pen" place="intext" language="LA" text="mensuraru[m]"/>
        <mark name="dot" method="pen" place="intext"/> <!--diximus, tum-->
        <mark name="equal_sign" method="pen" place="intext"/> <!-- loco- -->
        <mark name="equal_sign" method="pen" place="intext"/> <!-- h[a]ec-->
        <mark name="plus_sign" method="pen" place="intext" language="LA" text="certam"/>
        <mark name="dot" method="pen" place="intext"/> <!--co[n]plecti, ac-->
        <mark name="vertical_bar" method="pen" place="intext"/> <!--after intelligendis-->
        <mark name="dot" method="pen" place="intext"/> <!--autorem, quae-->
        <mark name="dot" method="pen" place="intext"/> <!--erant, eas-->        
        <mark name="equal_sign" method="pen" place="intext"/> <!-- uno ordine -->
        <mark name="plus_sign" method="pen" place="intext" language="LA" text="insignem[m]"/>
        <mark name="vertical_bar" method="pen" place="intext"/> <!--before Itaq[ue]-->
        
        
    </annotation>
</transcription>

=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/Livy/00000010.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE transcription SYSTEM "DTD10-10-2014.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../../Harvey/XML/Harveyschema17102014.xsd"> 
    <page filename="00000010.tif" signature="[a2v]" reader="Harvey" />
    <annotation>
        
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="intext" book_orientation="0">
                    <marginalia_text>1.</marginalia_text>
                </position>
            </language>        
        </marginalia>
        
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="intext" book_orientation="0">
                    <marginalia_text>2.</marginalia_text>
                </position>
            </language>        
        </marginalia>
        
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="intext" book_orientation="0">
                    <marginalia_text>3.</marginalia_text>
                </position>
            </language>        
        </marginalia>
        
        
        <underline method="pen" type="straight" language="LA" text="ego solus, qui" />
        <underline method="pen" type="straight" language="LA" text="doctos omnes" />
        <underline method="pen" type="straight" language="LA" text="in hoc dies noctes q[ue]; incumbant, elaborent, sudent" />
        <underline method="pen" type="straight" language="LA" text="maxim&egrave; historicos" />
        <underline method="pen" type="straight" language="LA" text="una re nihil utilius hominum generi" />
        <underline method="pen" type="straight" language="LA" text="nihil sibijpsi praeclarius facere" />
        <underline method="pen" type="straight" language="LA" text="simul ueteres disciplinas caput attollere coepisse: artium usum bonarum" />
        <underline method="pen" type="straight" language="LA" text="musas" />
        <underline method="pen" type="straight" language="LA" text="coniunctis manibus" />
        <underline method="pen" type="straight" language="LA" text="coniunctis animis" />
        <underline method="pen" type="straight" language="LA" text="humani generis uiniculum benuolentia"/>
        <underline method="pen" type="straight" language="LA" text="illa aurea felixq[ue]"/>
        <underline method="pen" type="straight" language="LA" text="mod&ograve; linquis sauere"/>
        <underline method="pen" type="straight" language="LA" text="etiam liberalitate"/>
        <underline method="pen" type="straight" language="LA" text="omni re gerenda duo requirantur"/>
        <underline method="pen" type="straight" language="LA" text="voluntas"/>
        <underline method="pen" type="straight" language="LA" text="facultas, nec altera sine altera quiqua[m] possit efficere" />
        <underline method="pen" type="straight" language="LA" text="ista duo co[n]iungenda" />
        <underline method="pen" type="straight" language="LA" text="Voluntas in bonis doctisq[ue]" />
        <underline method="pen" type="straight" language="LA" text="diuitibus facultas" />
        <underline method="pen" type="straight" language="LA" text="dijs erunt &amps; hominibus inuisi" />
        <underline method="pen" type="straight" language="LA" text="rerum cognoscere causus" />
        <underline method="pen" type="straight" language="LA" text="alium qui recta" />
        <underline method="pen" type="straight" language="LA" text="non consultis ipse" />
        <underline method="pen" type="straight" language="LA" text="voces contemnere" />
        <underline method="pen" type="straight" language="LA" text="inuisus diuis, &amp; inutilis" />
        
        <symbol name="SS" place="left_margin"/>
        
        <mark name="quotation_mark" method="pen" place="left_margin"/> 
        <mark name="bracket" method="pen" place="left_margin"/>
        
        <mark name="dash" method="pen" place="right_margin"/> <!-- om -->
        <mark name="quotation_mark" method="pen" place="right_margin"/> <!-- om -->
        <mark name="dash" method="pen" place="right_margin"/> <!-- pie -->
        <mark name="dash" method="pen" place="right_margin"/> <!-- uo -->
        
        <mark name="dot" method="pen" place="intext"/> <!-- cuiusquam, ut-->
        <mark name="dot" method="pen" place="intext"/> <!-- historicos, qua-->
        <mark name="plus_sign" method="pen" place="intext"/> <!-- artium, usum-->
        <mark name="dot" method="pen" place="intext"/> <!-- opera[m], spero-->
        <mark name="dot" method="pen" place="intext"/> <!-- primum, deinde-->
        <mark name="dot" method="pen" place="intext"/> <!-- artes, in-->
        <mark name="dot" method="pen" place="intext"/> <!-- rati, paucissimi-->
        <!--JG: accent above minus in the penultimate line-->
        <mark name="equal_sign" method="pen" place="intext"/> <!-- felix-->
        <mark name="equal_sign" method="pen" place="intext"/> <!-- orbi est -->
        
    </annotation>
</transcription>
