=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/DTD10-10-2014.dtd
<!ELEMENT transcription (page, annotation)>
<!ELEMENT page EMPTY>
	<!ATTLIST page filename CDATA #REQUIRED>
	<!ATTLIST page pagination CDATA #IMPLIED>
	<!ATTLIST page signature CDATA #IMPLIED>
	<!ATTLIST page reader CDATA #REQUIRED>

<!ELEMENT annotation (marginalia*, underline*, symbol*, mark*)>	
	<!ELEMENT marginalia (language*, translation?)>
	<!ATTLIST marginalia hand (English_secretary|Italian) #REQUIRED>
	<!ATTLIST marginalia date CDATA #IMPLIED>
	<!ATTLIST marginalia other_reader CDATA #IMPLIED>
	<!ATTLIST marginalia topic (Law|Astronomy|Warfare|Rhetoric) #IMPLIED> 
	<!ATTLIST marginalia anchor_text CDATA #IMPLIED>
	 	<!ELEMENT language (position*)>
			<!ATTLIST language ident (EN|EL|FR|IT|LA|ES) #REQUIRED> 
				<!ELEMENT position (marginalia_text*, person*, book*, location*, X-ref*, emphasis*)>
					<!ATTLIST position place (head|tail|left_margin|right_margin|intext|full_page) #REQUIRED>
					<!ATTLIST position book_orientation	(0|90|180|270) #REQUIRED>
						<!ELEMENT marginalia_text (#PCDATA)>
						<!ELEMENT person EMPTY>
							<!ATTLIST person name CDATA #REQUIRED>
						<!ELEMENT book EMPTY>
							<!ATTLIST book title CDATA #REQUIRED>
						<!ELEMENT location EMPTY>
							<!ATTLIST location name CDATA #REQUIRED>
						<!ELEMENT X-ref EMPTY>
							<!ATTLIST X-ref person CDATA #REQUIRED>
							<!ATTLIST X-ref book_title CDATA #REQUIRED>
						<!ELEMENT emphasis EMPTY> 
							<!ATTLIST emphasis method (chalk|pen) #REQUIRED>
							<!ATTLIST emphasis text CDATA #IMPLIED>
		<!ELEMENT translation (#PCDATA)>
	<!ELEMENT underline EMPTY>
		<!ATTLIST underline method (chalk|pen) #REQUIRED>
		<!ATTLIST underline type (straight|curved) #REQUIRED>
		<!ATTLIST underline language (EN|EL|FR|IT|LA|ES) #REQUIRED>
		<!ATTLIST underline text CDATA #IMPLIED> 
	<!ELEMENT symbol EMPTY>
		<!ATTLIST symbol name (Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun) #REQUIRED>
		<!ATTLIST symbol place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST symbol language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST symbol text CDATA #IMPLIED>
	<!ELEMENT mark EMPTY>
		<!ATTLIST mark name	(apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign) #REQUIRED>
		<!ATTLIST mark method (chalk|pen) #REQUIRED>
		<!ATTLIST mark place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST mark language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST mark text CDATA #IMPLIED>
			
<!ENTITY agrave "à">
<!ENTITY aacute "á">
<!ENTITY atiled "ã">
<!ENTITY egrave "è">
<!ENTITY eacute "é">
<!ENTITY ecirc "ê">
<!ENTITY igrave "ì">
<!ENTITY ograve "ò">
<!ENTITY oacute "ó">
<!ENTITY Ocirc "Ô">
<!ENTITY euml "ë">
<!ENTITY ugrave "ù">

=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/Domenichi/Ha2.014r.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE transcription SYSTEM "DTD10-10-2014.dtd">

<transcription>

	<page filename="Ha2.014r.tif" pagination="347" reader="Harvey"/>	<!-- ABO  018right -->
    	<annotation>
    		
            	<!-- Marginalia -->
    		
        		<marginalia hand="Italian">
        			<language ident="LA">
        				<position place="head" book_orientation="0">
                    				<marginalia_text>
                    					Autotechnia, et Cosmopraxia Vnica.
                    				</marginalia_text>
        				</position>
        			</language>
        		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						s[upr]a / 
    					</marginalia_text>
    				</position>
    			</language>
    			<language ident="IT">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						dilemma. (
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						Ca[e]teri omnes nugas agut.
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						plures Doctores, pro, an contra?
    						pro se, qua[e]q[ue] secta.
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						( Solus polytechnus non nugatur.
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="tail" book_orientation="0">
    					<marginalia_text>
    						A radice ad fructum: aut
    						opera perdita.
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
        
        
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="left_margin" book_orientation="270">
    					<marginalia_text>
    						Extentu proprio multiplicare [docet]. Huc arcana acma[e], stratagemataq[ue] eruta ab alto:	<!-- Word unclear: docet or decet. This marginal note also continues elsewhere, possibly gutter of facing page. Requires further investigation. -->
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
    		
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="right_margin" book_orientation="270">
    					<marginalia_text>
    						Autotechni, et Cosmopragmatici Archignomicon.. Parcus uesc[e]ndi: parcissimus esto bibendi:
    						Parcior [e]t somni: parcior [a]t Veneris. Prodigus at solia studij, techna[e]q[ue] profundia[e],
    						Pra[e]ualidiq[ue] actus, omnigeniq[ue] boni. Talis ego Parcus, talisq[ue] ego Prodigus omnes
    						Abijcio nugas: pragmata stricta premo. Quod potis est ars, aut virtus, aut =
    						
    					</marginalia_text>
    				</position>
    				<position place="intext" book_orientation="270">
    					<marginalia_text>
    						= da[e]dala praxis, Extentu
    					</marginalia_text>
    					<person name="Daedalus"/>
    				</position>
    			</language>
    		</marginalia>
    		
    		
        
	    	<!-- Underlines -->
	        
	    	<underline method="pen" type="straight" language="IT" text="347."/>
    		<underline method="pen" type="straight" language="IT" text="uscirne in sabbato"/>
    		<underline method="pen" type="straight" language="IT" text="la Domenica"/>
    		<underline method="pen" type="straight" language="IT" text="Hebreo"/>
    		<underline method="pen" type="straight" language="IT" text="Christiano"/>
    		<underline method="pen" type="straight" language="IT" text="Hebrei"/>
    		<underline method="pen" type="straight" language="IT" text="pi&ugrave; santi in"/>
    		<underline method="pen" type="straight" language="IT" text="contare i"/>
    		<underline method="pen" type="straight" language="IT" text="cauare un pelo del"/>
    		<underline method="pen" type="straight" language="IT" text="barba all'altro"/>
    		<underline method="pen" type="straight" language="IT" text="l'Hebreo"/>
    		<underline method="pen" type="straight" language="IT" text="Abraam"/>
    		<underline method="pen" type="straight" language="IT" text="Pietro"/>
    		<underline method="pen" type="straight" language="IT" text="seguita[n]do per ordine parecchi l'un"/>
    		<underline method="pen" type="straight" language="IT" text="Christiano fastidito"/>
    		<underline method="pen" type="straight" language="IT" text="alla barba al Giudeo"/>
    		<underline method="pen" type="straight" language="IT" text="strappogliela tutta"/>
    		<underline method="pen" type="straight" language="IT" text="Santa Orsola con la sua compagnia"/>
    		<underline method="pen" type="straight" language="IT" text="scolare Pesciatino"/>
    		<underline method="pen" type="straight" language="IT" text="moccichino in"/>
    		<underline method="pen" type="straight" language="IT" text="Niccoletta Cortigiana"/>
    		<underline method="pen" type="straight" language="IT" text="io no[n] u'inte[n]do"/>
    		<underline method="pen" type="straight" language="IT" text="pure a inte[n]dere"/>
    		<underline method="pen" type="straight" language="IT" text="buoni orecchi"/>
    		<underline method="pen" type="straight" language="IT" text="be[n] forati"/>
    		<underline method="pen" type="straight" language="IT" text="gli orecchi gra[n]di"/>
    		<underline method="pen" type="straight" language="IT" text="pie[n] d'annelletti d'oro"/>
    		<underline method="pen" type="straight" language="IT" text="Arguto"/>
    		<underline method="pen" type="straight" language="IT" text="scolar Pesciatino"/>
    		<underline method="pen" type="straight" language="IT" text="uolte per burla"/>
    		<underline method="pen" type="straight" language="IT" text="battaglie a una cortigiana"/>
    		<underline method="pen" type="straight" language="IT" text="innamorato"/>
    		<underline method="pen" type="straight" language="IT" text="uoler dormire"/>
    		<underline method="pen" type="straight" language="IT" text="ella non gli"/>
    		<underline method="pen" type="straight" language="IT" text="mai dato udienza"/>
    		<underline method="pen" type="straight" language="IT" text="offerendole che"/>
    		
	       
	       
	    	<!-- Symbols: Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun -->
	      		
	    	<!-- Marks: apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign -->
	    	
	    	<!-- Right margin -->
	    	<mark name="dash" method="pen" place="right_margin"/> <!-- Domeni -->
    		<mark name="plus_sign" method="pen" place="right_margin"/> <!-- un pelo del -->
    		<mark name="dash" method="pen" place="right_margin"/> <!-- cam -->
    		<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- tutta, di- -->
    		<mark name="dash" method="pen" place="right_margin"/> <!-- ridomandando -->
    		
	    	<!-- Left margin -->
	    	<mark name="bracket" method="pen" place="left_margin"/> <!-- lecito .. ca -->
    		<mark name="bracket" method="pen" place="left_margin"/> <!-- po Abraam ... po l'altro -->
		    
	    	<!-- Intext -->
    		<mark name="plus_sign" method="pen" place="intext" language="IT" text="Hebrei"/> 
	    	<mark name="dot" method="pen" place="intext"/> <!-- i suoi, e ogni -->
    		<mark name="vertical_bar" method="pen" place="intext"/> <!-- Christiano: e il -->
    		<mark name="plus_sign" method="pen" place="intext"/> <!-- ordine parecchi -->
    		<mark name="quotation_mark" method="pen" place="intext"/> <!-- Christiano fastidito -->
    		<mark name="comma" method="pen" place="intext"/> <!-- al Giudeo & -->
    		<mark name="equal_sign" method="pen" place="intext"/> <!-- Santa Orsola -->
    		<mark name="plus_sign" method="pen" place="intext" language="IT" text="forati"/>
    		<mark name="plus_sign" method="pen" place="intext" language="IT" text="Arguto"/>
    		
    		

    </annotation>
</transcription>

=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/Domenichi/Ha2.016r.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE transcription SYSTEM "DTD10-10-2014.dtd">

<transcription>

	<page filename="Ha2.016r.tif" pagination="351" reader="Harvey"/>	<!-- ABO 020right  -->
    	<annotation>
    		
            		<!-- Marginalia -->
    		
        		<marginalia hand="Italian">
        			<language ident="EN">
            			               <position place="head" book_orientation="0">
                    				<marginalia_text>
                    					The best do but well: none well enough.
                    				</marginalia_text>
            			               	<emphasis method="chalk"/>
            			               </position>
        			</language>
        		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						s[upr]a /
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="LA">
    				<position place="intext" book_orientation="0">
    					<marginalia_text>
    						Multi magnates: pauci magni.
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
    		<marginalia hand="Italian">
    			<language ident="EN">
    				<position place="tail" book_orientation="0">
    					<marginalia_text>
    						( No man is mean: if a right man.)
    						Of Kingdoms prouinced: a saying
    						of Orient.
    					</marginalia_text>
    					<location name="Orient"/>
    					<emphasis method="chalk" text="mean"/>
    				</position>
    			</language>
    		</marginalia>
    		
    		
    		<marginalia hand="Italian">
    			<language ident="EN">
    				<position place="right_margin" book_orientation="270">
    					<marginalia_text>
    						What say you to the Preists, that presume to prouincialise the mightiest kingdoms
    						vpon Earth, not to the Empire, but to the Popedum: &amp; deuise such statelie
    						designes, to inuest the bishop of Roome, The vniuersal monarch of the World? =
    					</marginalia_text>
    					<emphasis method="chalk"/>
    				</position>
    				<position place="left_margin" book_orientation="270">
    					<marginalia_text>
    						= Aspiring to a greater maiestie, then euer Alexander the Great, or greater Cesar
    						[vsurped]. Do you not think them holie preists, that can plat[f]orme such [-]	<!-- This marginalia seems to continue into the right margin of the facing page. -->
    					</marginalia_text>
    				</position>
    			</language>
    		</marginalia>
    		
    		<!-- MISSING TEXT: ILLEGIBLE DUE TO BENT PAGE. ORIGINAL SOURCE NEEDED-->
    		
	    	<!-- Underlines -->
    		<underline method="pen" type="straight" language="IT" text="ambasciate"/>
    		<underline method="pen" type="straight" language="IT" text="infastidito da una uedoua"/>
    		<underline method="pen" type="straight" language="IT" text="Pesciatina"/>
    		<underline method="pen" type="straight" language="IT" text="era guasta di lui"/>
    		<underline method="pen" type="straight" language="IT" text="dite a Madonna"/>
    		<underline method="pen" type="straight" language="IT" text="io spenda il mio"/>
    		<underline method="pen" type="straight" language="IT" text="beni sodi"/>
    		<underline method="pen" type="straight" language="IT" text="mi togliete piu il capo"/>
    		<underline method="pen" type="straight" language="IT" text="Alfonso de' Pazzi"/>
    		<underline method="pen" type="straight" language="IT" text="di Siena"/>
    		<underline method="pen" type="straight" language="IT" text="di sei"/>
    		<underline method="pen" type="straight" language="IT" text="chiamati Signori"/>
    		<underline method="pen" type="straight" language="IT" text="suprema auttorit&agrave; sopra"/>
    		<underline method="pen" type="straight" language="IT" text="sopra il suo stato"/>
    		<underline method="pen" type="straight" language="IT" text="di due mesi"/>
    		<underline method="pen" type="straight" language="IT" text="che un di quei Signori"/>
    		<underline method="pen" type="straight" language="IT" text="un giorno solo hauea sopra de gli altri suoi"/>
    		<underline method="pen" type="straight" language="IT" text="di fargli ragunare"/>
    		<underline method="pen" type="straight" language="IT" text="proporre le cose occorrenti, &amp; appartene[n]ti a quello"/>
    		<underline method="pen" type="straight" language="IT" text="faceua in commune"/>
    		<underline method="pen" type="straight" language="IT" text="bello e"/>
    		<underline method="pen" type="straight" language="IT" text="accommodato ragionamento rinuntiaua la sua auttorit&agrave;"/>
    		<underline method="pen" type="straight" language="IT" text="presenta[n]dogli per segno"/>
    		<underline method="pen" type="straight" language="IT" text="mazza d'auorio"/>
    		<underline method="pen" type="straight" language="IT" text="Pandolfo Petrucci"/>
    		<underline method="pen" type="straight" language="IT" text="col suo astuto ingeno, &amp; affabile natura"/>
    		<underline method="pen" type="straight" language="IT" text="haueua acquistata una piaceuole tira[n]nide"/>
    		<underline method="pen" type="straight" language="IT" text="istessa citt&agrave;"/>
    		<underline method="pen" type="straight" language="IT" text="famiglia de' Buoninsegni, il"/>
    		<underline method="pen" type="straight" language="IT" text="alhora de' deti Signori"/>
    		<underline method="pen" type="straight" language="IT" text="rinuntiare l'auttorit&agrave;"/>
    		<underline method="pen" type="straight" language="IT" text="un bel esordio"/>
    		<underline method="pen" type="straight" language="IT" text="cominci&ograve; a narrare"/>
    		<underline method="pen" type="straight" language="IT" text="Dio permesso a Satanasso"/>
    		<underline method="pen" type="straight" language="IT" text="Giobbe"/>
    		<underline method="pen" type="straight" language="IT" text="Satanasso lo priu&ograve; de' frutti"/>
    	       
	    	<!-- Symbols: Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun -->
	        
	    	<symbol name="JC" place="intext"/>
    		<symbol name="SS" place="right_margin"/>
	      		
	    	<!-- Marks: apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign -->
	    	
	    	<!-- Right margin -->
	    	<mark name="dash" method="pen" place="right_margin"/> <!-- ispa -->
	    	<mark name="X_sign" method="pen" place="right_margin"/> <!-- ordinati -->
    		<mark name="dash" method="pen" place="right_margin"/> <!-- quel -->
    		<mark name="dash" method="pen" place="right_margin"/> <!-- ce -->
    		<mark name="dash" method="pen" place="right_margin"/> <!-- na -->
    		<mark name="dash" method="pen" place="right_margin"/> <!-- quel -->
    		
	    	<!-- Left margin -->
	    	<mark name="plus_sign" method="pen" place="left_margin"/> <!-- in beni sodi -->
    		<mark name="bracket" method="pen" place="left_margin"/> <!-- piccola ... insegni-->
		    
	    	<!-- Intext -->
	    	<mark name="plus_sign" method="pen" place="intext" language="IT" text="uedoua"/>
    		<mark name="dot" method="pen" place="intext"/> <!-- di lui, il quale -->
    		<mark name="plus_sign" method="pen" place="intext" language="IT" text="suprema"/>
    		<mark name="plus_sign" method="pen" place="intext"/> <!-- suo stato -->
    		<mark name="plus_sign" method="pen" place="intext"/> <!-- un di quei -->
    		<mark name="plus_sign" method="pen" place="intext"/> <!-- giorno solo -->
    		<mark name="plus_sign" method="pen" place="intext"/> <!-- ragionamento rinuntiava --> 
    		<mark name="dot" method="pen" place="intext"/> <!-- compagni, presentandogli -->
    		<mark name="vertical_bar" method="pen" place="intext"/> <!-- d'auorio. Avve[n]ne -->
    		<mark name="plus_sign" method="pen" place="intext"/> <!-- astuto ingeno -->
    		<mark name="plus_sign" method="pen" place="intext"/> <!-- affabile -->
    		<mark name="equal_sign" method="pen" place="intext"/> <!-- piaceuole tira[n]nide -->
    		<mark name="vertical_bar" method="chalk" place="intext"/> <!-- chalk mark through middle of page -->
    		<mark name="plus_sign" method="pen" place="intext"/> <!-- rinuntiare l'auttorita' -->
    		<mark name="dot" method="pen" place="intext"/> <!-- compagno, dopo' un bel -->
    		<mark name="vertical_bar" method="pen" place="intext"/> <!-- a narrare, come -->

    </annotation>
</transcription>

=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/Domenichi/Ha2.009v.xml
<?xml version="1.0" standalone="no" ?>

<!DOCTYPE transcription SYSTEM "DTD10-10-2014.dtd">

<transcription>
    <page filename="Ha2.009v.tif" pagination="338" reader="Harvey"/>	<!-- ABO 14left -->
    <annotation>
        
        <!-- Marginalia -->
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="head" book_orientation="0">
                    <marginalia_text>
                      Vita Philotimi.
                    </marginalia_text>
                	<person name="Philotimus"/>
                </position>
            </language>
        </marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					Corruptio vnius, generatio alterius. 
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					Quid pro quo: sed minus pro maiori.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					ridicolo.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					Caesaris, et Alexandri φιλοπρωτία in omni ge[-] <!-- MISSING TEXT: ILLEGIBLE DUE TO BENT PAGE. ORIGINAL SOURCE NEEDED-->
    				</marginalia_text>
    				<person name="Julius Caesar"/>
    				<person name="Alexander the Great"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					Borgiae Emblema: Aut Caesar aut nihil.
    				</marginalia_text>
    				<person name="Borgia"/> 
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					Ecc&egrave; elogiu[m] Iouij: Icon Guicciar.
    				</marginalia_text>
    				<person name="Jupiter"/>
    				<person name="Francesco Guicciardini"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="left_margin" book_orientation="90">
    				<marginalia_text>
    					Faelix est, qui agit vtilia; aut legit necessaria. Miser, qui otiatur inutiliter; aut scribit
    					non necessaria.
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="left_margin" book_orientation="90">
    				<marginalia_text>
    					{ Sola mihi vita est, verbis, factisq[ue] praeire;
    					Anticipare omnes; summa parare breu&egrave;. } 
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
    	
	<!-- MISSING TEXT: ILLEGIBLE DUE TO BENT PAGE. ORIGINAL SOURCE NEEDED-->
    	
        
        <!-- Underlines -->
        
    	<underline method="pen" type="straight" language="IT" text="perduto il coltello"/>
    	<underline method="pen" type="straight" language="IT" text="rimetteua un'altro di legno in luogo"/>
    	<underline method="pen" type="straight" language="IT" text="Galeotto da Narni"/>
    	<underline method="pen" type="straight" language="IT" text="frati Inquisitori"/>
    	<underline method="pen" type="straight" language="IT" text="Heresia"/>
    	<underline method="pen" type="straight" language="IT" text="a un tribunale"/>
    	<underline method="pen" type="straight" language="IT" text="si ridicesse di quel"/>
    	<underline method="pen" type="straight" language="IT" text="perdono"/>
    	<underline method="pen" type="straight" language="IT" text="subito riso"/>
    	<underline method="pen" type="straight" language="IT" text="mise sotto sopra quel giuditio"/>
    	<underline method="pen" type="straight" language="IT" text="grandissimo"/>
    	<underline method="pen" type="straight" language="IT" text="dishonesta uita della moglie"/>
    	<underline method="pen" type="straight" language="IT" text="passar Galeotto"/>
    	<underline method="pen" type="straight" language="IT" text="porco grasso"/>
    	<underline method="pen" type="straight" language="IT" text="uolto allegro, &amp; ridente"/>
    	<underline method="pen" type="straight" language="IT" text="un porco grasso"/>
    	<underline method="pen" type="straight" language="IT" text="becco magro"/>
    	<underline method="pen" type="straight" language="IT" text="Galeotto"/>
    	<underline method="pen" type="straight" language="IT" text="tanto sconciamente grasso"/>
    	<underline method="pen" type="straight" language="IT" text="gran cauallo, o mulo non lo poteua portare"/>
    	<underline method="pen" type="straight" language="IT" text="una carretta"/>
    	<underline method="pen" type="straight" language="IT" text="monsignore Egnatio"/>
    	<underline method="pen" type="straight" language="IT" text="Lodouico undecimo"/>
    	<underline method="pen" type="straight" language="IT" text="riceuuto in dono"/>
    	<underline method="pen" type="straight" language="IT" text="dieci mila scudi"/>
    	<underline method="pen" type="straight" language="IT" text="gli ufficiali"/>
    	<underline method="pen" type="straight" language="IT" text="u'uccellano"/>
    	<underline method="pen" type="straight" language="IT" text="piu le speranze d'ogniuno"/>
    	
    
        
        <!-- Symbols: Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun -->
        
        <symbol name="Sun" place="head"/>
    	<symbol name="JC" place="left_margin"/>
        
        <!-- Marks: apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|tilde|triple_dash|vertical_bar|X_sign -->
    	
    	<!-- Right margin -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- Pa -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- guai -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- doma[n] -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- riso -->
    	<mark name="bracket" method="pen" place="right_margin"/> <!-- gli ... grasso, -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- po -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- car -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- riceuu -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- quan -->
    	
    	<!-- Left margin -->
    	<mark name="bracket" method="pen" place="left_margin"/> <!-- pa ... na, ne -->
    	<mark name="plus_sign" method="pen" place="left_margin"/> <!-- per lo quale -->
    	<mark name="quotation_mark" method="pen" place="left_margin"/> <!-- dasse -->
    	<mark name="quotation_mark" method="pen" place="left_margin"/> <!-- rispose -->
    	<mark name="plus_sign" method="pen" place="left_margin"/> <!-- u'uccellano -->
    
    	<!-- Intext -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- di quello. -->
    	<mark name="equal_sign" method="pen" place="intext" language="IT" text="Heresia"/>
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- sotto sopra. -->
    	<mark name="quotation_mark" method="pen" place="intext"/> <!-- uolto allegro -->

    </annotation>
</transcription>
