=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/DTD10-10-2014.dtd
<!ELEMENT transcription (page, annotation)>
<!ELEMENT page EMPTY>
	<!ATTLIST page filename CDATA #REQUIRED>
	<!ATTLIST page pagination CDATA #IMPLIED>
	<!ATTLIST page signature CDATA #IMPLIED>
	<!ATTLIST page reader CDATA #REQUIRED>

<!ELEMENT annotation (marginalia*, underline*, symbol*, mark*)>	
	<!ELEMENT marginalia (language*, translation?)>
	<!ATTLIST marginalia hand (English_secretary|Italian) #REQUIRED>
	<!ATTLIST marginalia date CDATA #IMPLIED>
	<!ATTLIST marginalia other_reader CDATA #IMPLIED>
	<!ATTLIST marginalia topic (Law|Astronomy|Warfare|Rhetoric) #IMPLIED> 
	<!ATTLIST marginalia anchor_text CDATA #IMPLIED>
	 	<!ELEMENT language (position*)>
			<!ATTLIST language ident (EN|EL|FR|IT|LA|ES) #REQUIRED> 
				<!ELEMENT position (marginalia_text*, person*, book*, location*, X-ref*, emphasis*)>
					<!ATTLIST position place (head|tail|left_margin|right_margin|intext|full_page) #REQUIRED>
					<!ATTLIST position book_orientation	(0|90|180|270) #REQUIRED>
						<!ELEMENT marginalia_text (#PCDATA)>
						<!ELEMENT person EMPTY>
							<!ATTLIST person name CDATA #REQUIRED>
						<!ELEMENT book EMPTY>
							<!ATTLIST book title CDATA #REQUIRED>
						<!ELEMENT location EMPTY>
							<!ATTLIST location name CDATA #REQUIRED>
						<!ELEMENT X-ref EMPTY>
							<!ATTLIST X-ref person CDATA #REQUIRED>
							<!ATTLIST X-ref book_title CDATA #REQUIRED>
						<!ELEMENT emphasis EMPTY> 
							<!ATTLIST emphasis method (chalk|pen) #REQUIRED>
							<!ATTLIST emphasis text CDATA #IMPLIED>
		<!ELEMENT translation (#PCDATA)>
	<!ELEMENT underline EMPTY>
		<!ATTLIST underline method (chalk|pen) #REQUIRED>
		<!ATTLIST underline type (straight|curved) #REQUIRED>
		<!ATTLIST underline language (EN|EL|FR|IT|LA|ES) #REQUIRED>
		<!ATTLIST underline text CDATA #IMPLIED> 
	<!ELEMENT symbol EMPTY>
		<!ATTLIST symbol name (Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun) #REQUIRED>
		<!ATTLIST symbol place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST symbol language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST symbol text CDATA #IMPLIED>
	<!ELEMENT mark EMPTY>
		<!ATTLIST mark name	(apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|straight_quotation_mark|tilde|triple_dash|vertical_bar|X_sign) #REQUIRED>
		<!ATTLIST mark method (chalk|pen) #REQUIRED>
		<!ATTLIST mark place (head|tail|left_margin|right_margin|intext) #REQUIRED>
		<!ATTLIST mark language (EN|EL|FR|IT|LA|ES) #IMPLIED>
		<!ATTLIST mark text CDATA #IMPLIED>
			
<!ENTITY agrave "à">
<!ENTITY aacute "á">
<!ENTITY atiled "ã">
<!ENTITY egrave "è">
<!ENTITY eacute "é">
<!ENTITY ecirc "ê">
<!ENTITY igrave "ì">
<!ENTITY ograve "ò">
<!ENTITY oacute "ó">
<!ENTITY Ocirc "Ô">
<!ENTITY euml "ë">
<!ENTITY ugrave "ù">

=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/Domenichi/Ha2.005v.xml
<?xml version="1.0" standalone="no" ?>

<!DOCTYPE transcription SYSTEM "DTD10-10-2014.dtd">

<transcription>
    <page filename="Ha2.005v.tif" pagination="330" reader="Harvey"/> <!-- ABO 10left -->
    <annotation>
        
        <!-- Marginalia -->
        <marginalia hand="Italian">
            <language ident="EN">
                <position place="head" book_orientation="0">
                    <marginalia_text>
                      Eutrapelus scornes himself, till he teaches all
                    </marginalia_text>
                	<person name="Eutrapelus"/>
                </position>
            	<position place="left_margin" book_orientation="0">
            		<marginalia_text>
            			other, to pronounce more
            		</marginalia_text>
            		<emphasis method="chalk"/>
            	</position>
            	<position place="intext" book_orientation="0">
            		<marginalia_text>
            			sensibly; to expresse more liuely; to speake
            		</marginalia_text>
            	</position>
            	<position place="left_margin" book_orientation="0">
            		<marginalia_text>
            			more effectually; to resolue &amp; persuade
            			more powrefully, 
            		</marginalia_text>
            	</position>
            	<position place="intext" book_orientation="0">
            		<marginalia_text>
            			then anie other heretofore.
            		</marginalia_text>
            	</position>
            </language>
        </marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					ridicolo. )
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					ridicolo.
    				</marginalia_text>
    			</position>
    		</language>
    		<language ident="LA">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					problemata, et aenigmata plebea. )
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					necessaria non necessarijs: prudens electio.
    					Hoc agit: nec curat parerga.
    				</marginalia_text>
    			</position>    			
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					ridicolo. fantastico.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					Lett Eutrapelus excell all other in speaking, designing
    					&amp; doing: or lett Eutrapelus be accounted a
    					meacock, &amp; a base fellow.
    				</marginalia_text>
    				<person name="Eutrapelus"/>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="left_margin" book_orientation="90">
    				<marginalia_text>
    					&Ocirc; sordide, vbi sunt aetheri spiritus?
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="right_margin" book_orientation="270">
    				<marginalia_text>
    					Alwais sum singularitie in action, or counsell: in speach, or behauiour.
    				</marginalia_text>
    				<emphasis method="chalk"/>
    			</position>
    		</language>
    	</marginalia>
        
        <!-- Underlines -->
        
    	<underline method="pen" type="straight" language="IT" text="si cerca"/>
    	<underline method="pen" type="straight" language="IT" text="uorrebbe trouare"/>
    	<underline method="pen" type="straight" language="IT" text="una ricamatrice"/>
    	<underline method="pen" type="straight" language="IT" text="la piu pulita arte"/>
    	<underline method="pen" type="straight" language="IT" text="Fornaciai, i quali"/>
    	<underline method="pen" type="straight" language="IT" text="cacare, che"/>
    	<underline method="pen" type="straight" language="IT" text="lauino prima le mani"/>
    	<underline method="pen" type="straight" language="IT" text="la lepre si"/>
    	<underline method="pen" type="straight" language="IT" text="guardare in dietro"/>
    	<underline method="pen" type="straight" language="IT" text="i cani le danno"/>
    	<underline method="pen" type="straight" language="IT" text="non ha gli occhi al culo"/>
    	<underline method="pen" type="straight" language="IT" text="Giuochi Carnascialeschi"/>
    	<underline method="pen" type="straight" language="IT" text="Giuliano de' Medici"/>
    	<underline method="pen" type="straight" language="IT" text="alla guardispensa"/>
    	<underline method="pen" type="straight" language="IT" text="gran Signore passaua"/>
    	<underline method="pen" type="straight" language="IT" text="si passi: io uu&ograve; cacare"/>
    	<underline method="pen" type="straight" language="IT" text="gi&agrave; in prouerbio"/>
    	<underline method="pen" type="straight" language="IT" text="Puossi scusare"/>
    	<underline method="pen" type="straight" language="IT" text="nuouo pesce"/>
    	<underline method="pen" type="straight" language="IT" text="Lionardo"/>
    	<underline method="pen" type="straight" language="IT" text="Aretino"/>
    	<underline method="pen" type="straight" language="IT" text="Carluzzo"/>
    	<underline method="pen" type="straight" language="IT" text="Lionardazzo"/>
    	<underline method="pen" type="straight" language="IT" text="h&ograve; parecchi lettere Greghe"/>
    	<underline method="pen" type="straight" language="IT" text="tutti nel merdazzo"/>
    	<underline method="pen" type="straight" language="IT" text="Greche"/>
    	<underline method="pen" type="straight" language="IT" text="andare in Costantinopoli"/>
    	<underline method="pen" type="straight" language="IT" text="inciampato a Napoli"/>
    	<underline method="pen" type="straight" language="IT" text="s'innamor&ograve; di non"/>
    	<underline method="pen" type="straight" language="IT" text="quiui spese tutti i suoi denari"/>
    	<underline method="pen" type="straight" language="IT" text="scusso a Fiorenza"/>
    	<underline method="pen" type="straight" language="IT" text="sempre soggiungeua"/>
    	<underline method="pen" type="straight" language="IT" text="lettere Greghe"/>
    	<underline method="pen" type="straight" language="IT" text="appar&ograve; il Barghella"/>
    	
        <!-- Symbols: Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun -->
        <!-- No apparent symbols -->
        
    	<!-- Marks: apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|tilde|triple_dash|vertical_bar|X_sign -->
    	<!-- Right margin -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- l'huo -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- ri -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- fa -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- dis -->
    	<mark name="plus_sign" method="pen" place="right_margin"/> <!-- cacare; & -->
    	<mark name="bracket" method="pen" place="right_margin"/> <!-- soleua ... lettere -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- io non -->
    	<mark name="quotation_mark" method="pen" place="right_margin"/> <!-- Greghe, -->
    	
    	<!-- Left margin -->
    	<mark name="quotation_mark" method="pen" place="left_margin" /> <!-- si lauino -->
    	<mark name="bracket" method="pen" place="left_margin" /> <!-- questo .. un fanciullo -->
    	<mark name="equal_sign" method="pen" place="left_margin" /> <!-- re passaua -->
    	<mark name="quotation_mark" method="pen" place="left_margin" /> <!-- & Lionardazzo -->
    	<mark name="vertical_bar" method="pen" place="left_margin" />
    	<mark name="bracket" method="pen" place="left_margin" /> <!-- pree ... che -->
    	    	
    	<!-- Intext -->
    	<mark name="vertical_bar" method="chalk" place="intext"/> <!-- Last paragraph on the left -->
    	<mark name="vertical_bar" method="chalk" place="intext"/> <!-- Last paragraph on the right -->
    	<mark name="plus_sign" method="pen" place="intext" text="cerca"/> <!--  -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- trouare. ] -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- piu pulita -->
    	<mark name="dot" method="pen" place="intext"/> <!-- sua, quelli -->
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- mani . Et -->
    	<mark name="dot" method="pen" place="intext"/> <!-- caccia, dis -->
    	<mark name="dot" method="pen" place="intext"/> <!-- passaua, & -->
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- ; & -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- fanciullo.] -->
    	<mark name="quotation_mark" method="pen" place="intext"/> <!-- & soleua -->
    	<mark name="dot" method="pen" place="intext"/> <!-- pesce, & -->
    	<mark name="quotation_mark" method="pen" place="intext"/> <!-- Straight quotes. Carluzzo, -->
    	<mark name="plus_sign" method="pen" place="intext"/> <!-- lettere Greghe -->
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- merdazzo. Et -->
        
    </annotation>
</transcription>

=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/Domenichi/Ha2.008v.xml
<?xml version="1.0" standalone="no" ?>

<!DOCTYPE transcription SYSTEM "DTD10-10-2014.dtd">

<transcription>
    <page filename="Ha2.008v.tif" pagination="336" reader="Harvey"/>	<!-- ABO 13left -->
    <annotation>
        
        <!-- Marginalia -->
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="head" book_orientation="0">
                    <marginalia_text>
                      Vita Astrophili.
                    </marginalia_text>
                	<person name="Astrophil"/>
                </position>
            </language>
        </marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="left_margin" book_orientation="0">
    				<marginalia_text>
    					Elixir vitae, Industria
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="IT">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					Problema ridicolo.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="intext" book_orientation="0">
    				<marginalia_text>
    					Euerie day better, &amp; better.
    				</marginalia_text>
    				<emphasis method="pen" text="Euerie"/>
    				<emphasis method="pen" text="better, &amp; better"/>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian" anchor_text="Pontano">
    		<language ident="IT">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					{ Pontano, nato a piaceuolezze.
    				</marginalia_text>
    				<person name="Giovanni Pontano"/>
    			</position>
    		</language>
    		<language ident="LA">
    			<position place="tail" book_orientation="0">
    				<marginalia_text>
    					) philosophus, philautus.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="left_margin" book_orientation="90">
    				<marginalia_text>
    					[mih]i vita est, essentia quinta valoris;
    					[-]s, virtus, praxis multiplicata potens. } 
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="EN">
    			<position place="right_margin" book_orientation="90">
    				<marginalia_text>
    					Manie [bigg] [??] are little worth: &amp; manie little men of great valour: 
    					<!-- MISSING TEXT: ILLEGIBLE DUE TO BENT PAGE. ORIGINAL SOURCE NEEDED -->
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="right_margin" book_orientation="270">
    				<marginalia_text>
    					tota in toto. res enim cum
    				</marginalia_text>
    			</position>
    			<position place="intext" book_orientation="270">
    				<marginalia_text>
    					Euschemosyne,    <!-- These do not seem to be names of people, as the first is Greek for "decorum," however I can't figure out "Fronismo," although the Greek root seems easy enough to guess. -->
    					et
    					Fronismo.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="left_margin" book_orientation="0">
    				<marginalia_text>
    					2.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
    	   	<marginalia hand="Italian">
    		<language ident="LA">
    			<position place="left_margin" book_orientation="0">
    				<marginalia_text>
    					3.
    				</marginalia_text>
    			</position>
    		</language>
    	</marginalia>
        
        <!-- Underlines -->
        
        <underline method="pen" type="straight" language="IT" text="tuttauia messere"/>
    	<underline method="pen" type="straight" language="IT" text="quella riuerentia"/>
    	<underline method="pen" type="straight" language="IT" text="messa"/>
    	<underline method="pen" type="straight" language="IT" text="canto rozo"/>
    	<underline method="pen" type="straight" language="IT" text="uillanesco"/>
    	<underline method="pen" type="straight" language="IT" text="altra donna"/>
    	<underline method="pen" type="straight" language="IT" text="nudo all'altare"/>
    	<underline method="pen" type="straight" language="IT" text="esser uestito"/>
    	<underline method="pen" type="straight" language="IT" text="la terza"/>
    	<underline method="pen" type="straight" language="IT" text="egli era morto"/>
    	<underline method="pen" type="straight" language="IT" text="sulla bara"/>
    	<underline method="pen" type="straight" language="IT" text="i suoi uicini"/>
    	<underline method="pen" type="straight" language="IT" text="frate"/>
    	<underline method="pen" type="straight" language="IT" text="ignudo"/>
    	<underline method="pen" type="straight" language="IT" text="no fussi morto"/>
    	<underline method="pen" type="straight" language="IT" text="mi riderei molto di"/>
    	<underline method="pen" type="straight" language="IT" text="queste pazzie de' miei"/>
    	<underline method="pen" type="straight" language="IT" text="queste tre donne habbia uinta la"/>
    	<underline method="pen" type="straight" language="IT" text="ingegnose quistioni"/>
    	<underline method="pen" type="straight" language="IT" text="le balie"/>
    	<underline method="pen" type="straight" language="IT" text="cantar delle"/>
    	<underline method="pen" type="straight" language="IT" text="il Pontano"/>
    	<underline method="pen" type="straight" language="IT" text="mirabilmente piaceuole in esprimere"/>
    	<underline method="pen" type="straight" language="IT" text="d'eloquentia, &amp; di dottrina con"/>
    	<underline method="pen" type="straight" language="IT" text="egli sia nato solamente a"/>
    	<underline method="pen" type="straight" language="IT" text="piaceuolezze"/>
    	
    
        
        <!-- Symbols: Asterisk|Bisected_circle|Crown|Crescent|JC|HT|LL|Mars|Mercury|Opposite_planets|Square|SS|Sun -->
        
        <symbol name="Sun" place="head"/>
    	<symbol name="Sun" place="head"/>
    	<symbol name="JC" place="intext"/>
    	<symbol name="SS" place="left_margin"/>
        
        <!-- Marks: apostrophe|box|bracket|circumflex|comma|dash|dot|equal_sign|hash|horizontal_bar|plus_sign|quotation_mark|semicolon|tilde|triple_dash|vertical_bar|X_sign -->
    	
    	<!-- Right margin -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- co -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- don -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- mira -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- pia -->
    	<mark name="dash" method="pen" place="right_margin"/> <!-- caminan -->
    	
    	<!-- Left margin -->
    	<mark name="quotation_mark" method="pen" place="left_margin"/> <!-- bilmente -->
    	<mark name="quotation_mark" method="pen" place="left_margin"/> <!-- ceuolezze -->
    
    	<!-- Intext -->
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- uillanesco; l'altra -->
    	<mark name="vertical_bar" method="pen" place="intext"/> <!-- uestito. Ma la terza -->
    	<mark name="dot" method="pen" place="intext"/> <!-- frate, & l'altro -->
    	<mark name="dot" method="pen" place="intext"/> <!-- l'offerta, disse -->
    	<mark name="plus_sign" method="pen" place="intext" language="IT" text="tre donne"/>
    	<mark name="quotation_mark" method="pen" place="intext"/> <!-- quistioni.] -->
    	<mark name="quotation_mark" method="pen" place="intext"/> <!-- Sogliono -->
    	<mark name="plus_sign" method="pen" place="intext" language="IT" text="Pontano"/>
    	<mark name="equal_sign" method="pen" place="intext" /> <!-- fu mira -->
    	<mark name="plus_sign" method="pen" place="intext" language="IT" text="nato"/>
    	<mark name="equal_sign" method="pen" place="intext" /> <!-- solamente -->
    	
    	<mark name="vertical_bar" method="chalk" place="intext"/> <!-- Middle of page to the left -->
    	<mark name="vertical_bar" method="chalk" place="intext"/> <!-- Bottom of page to the left -->

    </annotation>
</transcription>

=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/Livy/00000012.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE transcription SYSTEM "DTD10-10-2014.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/User1/Documents/GitHub/AORCLONEJG/XMLschema/Harveyschema17102014.xsd">
    
    <page filename="00000012.tif" signature="[a3v]" reader="Harvey" />
    <annotation>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="head" book_orientation="0">
                    <marginalia_text>Mensura[e] { Romanorum. Graecorum. </marginalia_text>
                </position>
            </language>
            <translation>Measures of the Romans of the Greeks.</translation>
        </marginalia>
        
        <underline method="pen" type="straight"  language="LA" text="LIQVORVM MENSVRAE"/>
        <underline method="pen" type="straight"  language="LA" text="ARIDORVM"/>
        
        <mark name="plus_sign" method="pen" place="head" text="MENSVRAE"/>
    </annotation>
</transcription>
