=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/XMLschema/Harveyschema22102014.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="transcription">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="page"/>
        <xs:element ref="annotation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="page">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.page"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.page">
    <xs:attribute name="filename" use="required"/>
    <xs:attribute name="pagination"/>
    <xs:attribute name="signature"/>
    <xs:attribute name="reader" use="required"/>
  </xs:attributeGroup>
  <xs:element name="annotation">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="marginalia"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="underline"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="symbol"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="mark"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="marginalia">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="language"/>
        <xs:element minOccurs="0" ref="translation"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.marginalia"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.marginalia">
    <xs:attribute name="hand" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="English_secretary"/>
          <xs:enumeration value="Italian"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="date"/>
    <xs:attribute name="other_reader"/>
    <xs:attribute name="topic">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Law"/>
          <xs:enumeration value="Astronomy"/>
          <xs:enumeration value="Warfare"/>
          <xs:enumeration value="Rhetoric"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="anchor_text"/>
  </xs:attributeGroup>
  <xs:element name="language">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="position"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.language"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.language">
    <xs:attribute name="ident" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="position">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="marginalia_text"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="person"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="book"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="location"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="X-ref"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="emphasis"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.position"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.position">
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
          <xs:enumeration value="full_page"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="book_orientation" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="0"/>
          <xs:enumeration value="90"/>
          <xs:enumeration value="180"/>
          <xs:enumeration value="270"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="marginalia_text" type="xs:string"/>
  <xs:element name="person">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.person"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.person">
    <xs:attribute name="name" use="required"/>
  </xs:attributeGroup>
  <xs:element name="book">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.book"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.book">
    <xs:attribute name="title" use="required"/>
  </xs:attributeGroup>
  <xs:element name="location">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.location"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.location">
    <xs:attribute name="name" use="required"/>
  </xs:attributeGroup>
  <xs:element name="X-ref">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.X-ref"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.X-ref">
    <xs:attribute name="person" use="required"/>
    <xs:attribute name="book_title" use="required"/>
  </xs:attributeGroup>
  <xs:element name="emphasis">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.emphasis"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.emphasis">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="translation" type="xs:string"/>
  <xs:element name="underline">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.underline"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.underline">
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="straight"/>
          <xs:enumeration value="curved"/>
          <xs:enumeration value="dotted"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="symbol">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.symbol"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.symbol">
    <xs:attribute name="name" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Asterisk"/>
          <xs:enumeration value="Bisected_circle"/>
          <xs:enumeration value="Crown"/>
          <xs:enumeration value="Crescent"/>
          <xs:enumeration value="JC"/>
          <xs:enumeration value="HT"/>
          <xs:enumeration value="LL"/>
          <xs:enumeration value="Mars"/>
          <xs:enumeration value="Mercury"/>
          <xs:enumeration value="Opposite_planets"/>
          <xs:enumeration value="Square"/>
          <xs:enumeration value="SS"/>
          <xs:enumeration value="Sun"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
  <xs:element name="mark">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.mark"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.mark">
    <xs:attribute name="name" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="apostrophe"/>
          <xs:enumeration value="box"/>
          <xs:enumeration value="bracket"/>
          <xs:enumeration value="circumflex"/>
          <xs:enumeration value="comma"/>
          <xs:enumeration value="dash"/>
          <xs:enumeration value="dot"/>
          <xs:enumeration value="equal_sign"/>
          <xs:enumeration value="hash"/>
          <xs:enumeration value="horizontal_bar"/>
          <xs:enumeration value="plus_sign"/>
          <xs:enumeration value="quotation_mark"/>
          <xs:enumeration value="semicolon"/>
          <xs:enumeration value="straight_quotation_mark"/>
          <xs:enumeration value="tilde"/>
          <xs:enumeration value="triple_dash"/>
          <xs:enumeration value="vertical_bar"/>
          <xs:enumeration value="X_sign"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="method" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="chalk"/>
          <xs:enumeration value="pen"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="place" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="head"/>
          <xs:enumeration value="tail"/>
          <xs:enumeration value="left_margin"/>
          <xs:enumeration value="right_margin"/>
          <xs:enumeration value="intext"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="language">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="EN"/>
          <xs:enumeration value="EL"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="ES"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="text"/>
  </xs:attributeGroup>
</xs:schema>

=== jhu-digital-manuscripts/rosa2/rosa-archive/rosa-archive-aor-tool/src/test/resources/archive/Livy/00000021.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE transcription SYSTEM "DTD10-10-2014.dtd">

<transcription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/User1/Documents/GitHub/AORCLONEJG/XMLschema/Harveyschema22102014.xsd">
    
    <page filename="00000021.tif" signature="[a8r]" reader="Harvey"  />
    <annotation>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="tail" book_orientation="0">
                    <marginalia_text>
                        Livii stylus: praesertim in concionibus.
                        Nullae Latinae, Graecaeve orationes, vel accurata lectione, vel exquisito delectu digniores quam Livianae conciones; a Perionio in artificiosum quendam 
                        ordinem redactae. Unde, cum orationibus vacat aut legendis, aut imitandis, aut etiam aemulandis, nullas iam malim, quam has, aut illas Livianas; 
                        tam sententia acres, quam elocutione limatas. Nihil plaerumque vel nervosius pressum, vel vividius expressum. Ut saepe ipse Atticismus hic superari videatur. 
                        Tam prudenter politus hic stylus: modo fusus splendide; modo strictus argute; modo scite temperatus: saepe adamantinus; semper gemmans, aut florens. 
                        Ni Caesarem, Sallustium, Virgilium intime nosset, mirarer tam nitidam pariter, solidamque componendi formulam: non magis illuminatam, 
                        quam seriam; nec minus subtilem, quam ornatam. Valde etiam placent quaedam rotunda, et arguta dicta: quasi Laconica apophtegmata. 
                        Nec unquam ferme deficit varietas: nec vigor fere uspiam flaccescit. Mea adhuc haec censura: nec in aliam sum, vel facile ducendus, 
                        vel solicite trahendus sententiam.
                    </marginalia_text>
                    <person name="Livy"/>
                    <person name="Joachim Perion"/>
                    <person name="Julius Caesar"/>
                    <person name="Sallust"/>
                    <person name="Virgil"/>
                    <book title="T. Livii Patavini Conciones"/>
                </position>
            </language>
            <translation>
                Livy's style, particularly in the speeches.
                There are no Latin or Greek orations that deserve more precise reading, or more special enjoyment than Livyâ€™s speeches, raised to some literary rank by Perionius. 
                Therefore, when I would have leisure for reading, imitating or emulating speeches, I would surely prefer no others than these or those of Livy, which are as sharp 
                in judgement as they are polished in expression. Generally nothing is more vigorously compressed or livelier expressed, so that often even Atticism itself 
                seems to be beaten here. His style is so sensibly polished, now marvelously copious, then ingeniously tight, or skilfully balanced; often steeled, 
                always brilliant or bright. If he were not intimately acquainted with Caesar, Sallust, and Virgil, I would marvel at such an equally refined and firm form of writing, 
                not just clear but also serious, and no less precise than rich. Very pleasing also are several well-turned and witty statements, as Laconic maxims. 
                Variety is almost never lacking and its vigor hardly ever falters. This is my judgment so far and I am not easily brought, or anxiously drawn, to another opinion.
            </translation>
        </marginalia>
        <marginalia hand="Italian"  anchor_text="Aeneas">
            <language ident="LA">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>AEneas.</marginalia_text>
                    <person name="Aeneas"/>
                </position>
            </language>
            <translation>Aeneas.</translation>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="left_margin" book_orientation="0">
                    <marginalia_text>I[nfr]a</marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian">
            <language ident="LA">
                <position place="intext" book_orientation="0">
                    <marginalia_text>I[nfr]a</marginalia_text>
                </position>
            </language>
        </marginalia>
        <marginalia hand="Italian"  anchor_text="Romulus">
            <language ident="LA">
                <position place="right_margin" book_orientation="0">
                    <marginalia_text>Romulus</marginalia_text>
                    <person name="Romulus" />
                </position>
            </language>
        </marginalia>
        
        
        <underline method="pen" type="straight" language="LA" text="lanum"/>
        <underline method="pen" type="straight" language="LA" text="in partem imperij est"/>
        <underline method="pen" type="straight" language="LA" text="lano defuncto"/>
        <underline method="pen" type="straight" language="LA" text="eum solum"/>
        <underline method="pen" type="straight" language="LA" text="Arcades ex urbe Palantio"/>
        <underline method="pen" type="straight" language="LA" text="duce Euandro"/>
        <underline method="pen" type="straight" language="LA" text="&agrave; Faunoq[ue] Aboriginum"/>
        <underline method="pen" type="straight" language="LA" text="Palantiumq[ue] &agrave; metropoli"/>
        <underline method="pen" type="straight" language="LA" text="classem Graecam, ducente Hercule, eandem tenuisse"/>
        <underline method="pen" type="straight" language="LA" text="Hos, Peloponnenses, &amp;"/>
        <underline method="pen" type="straight" language="LA" text="euersa eorum patria ab ipso Hercule"/>
        <underline method="pen" type="straight" language="LA" text="victum, leges, sacracum Aboriginibus confere[n]tes"/>
        <underline method="pen" type="straight" language="LA" text="Arcades, &amp; prius Pelasgi"/>
        <underline method="pen" type="straight" language="LA" text="Latino ex filia"/>
        <underline method="pen" type="straight" language="LA" text="Aeneas"/>
        <underline method="pen" type="straight" language="LA" text="statim praelio fuisset exceptus"/>
        <underline method="pen" type="straight" language="LA" text="colloquium &agrave; Latino fuit uocatus"/>
        <underline method="pen" type="straight" language="LA" text="tantam sui admirationem praebuit"/>
        <underline method="pen" type="straight" language="LA" text="societatem imperij"/>
        <underline method="pen" type="straight" language="LA" text="Aborigines, Troianosq[ue], communi"/>
        <underline method="pen" type="straight" language="LA" text="Latinos nominauit"/>
        <underline method="pen" type="straight" language="LA" text="Turnum"/>
        <underline method="pen" type="straight" language="LA" text="Aeneas soceri regnum suscipiens"/>
        <underline method="pen" type="straight" language="LA" text="bello aduersus Mezentium Hetruscorum regem, &egrave; uita"/>
        <underline method="pen" type="straight" language="LA" text="Albam"/>
        <underline method="pen" type="straight" language="LA" text="Syluius eius"/>
        <underline method="pen" type="straight" language="LA" text="Romulus"/>
        <underline method="pen" type="straight" language="LA" text="Rheam eius filiam"/>
        <underline method="pen" type="straight" language="LA" text="genere Numitoris"/>
        <underline method="pen" type="straight" language="LA" text="Vestae sacerdotem"/>
        <underline method="pen" type="straight" language="LA" text="duos pueros incerto stupro conceptos"/>
        <underline method="pen" type="straight" language="LA" text="fortuna origini Romanae prospiciens, eos lupae alendos"/>
        <underline method="pen" type="straight" language="LA" text="alteri Remo, alteri Romo, siue Romulo, fuere"/>
        <underline method="pen" type="straight" language="LA" text="de virtute"/>
        <underline method="pen" type="dotted" language="LA" text="quotidiana certamina"/>
        <underline method="pen" type="straight" language="LA" text="uires &amp; pernicitatem auxere"/>
        <underline method="pen" type="straight" language="LA" text="latrones &agrave; rapina pecorum"/>
        <underline method="pen" type="straight" language="LA" text="fact inter ipsos coniuratione, Amulium interficiunt, Numitoriq[ue] auo regnum restituunt"/>
        <underline method="pen" type="straight" language="LA" text="Roman, ubi expositifuerant, condiderunt"/>
        <underline method="pen" type="straight" language="LA" text="de tempore"/>
        <underline method="pen" type="straight" language="LA" text="de conditiore"/>
        <underline method="pen" type="straight" language="LA" text="scriptores uarietas"/>
        <underline method="pen" type="straight" language="LA" text="Romulum Martis"/>
        <underline method="pen" type="straight" language="LA" text="urbis autorem fuisse"/>
        <underline method="pen" type="straight" language="LA" text="urbis parens Romulus"/>
        <underline method="pen" type="straight" language="LA" text="optimus augur"/>
        <underline method="pen" type="straight" language="LA" text="Romulum"/>
        <underline method="pen" type="straight" language="LA" text="captatis augurijs"/>
        <underline method="pen" type="straight" language="LA" text="prior sex uultures"/>
        <underline method="pen" type="straight" language="LA" text="Romulus mox duodecim"/>
        <underline method="pen" type="straight" language="LA" text="tempore"/>
        <underline method="pen" type="straight" language="LA" text="numero certaret"/>
        <underline method="pen" type="straight" language="LA" text="Romulus &agrave; se Romam denominauit"/>
